### ISSUE TITLE
Not work with the same CPU

### ISSUE THREAD

**Issue by ItsMeMom** [khanhmuy/hackintosh-ideapad-3-14ABA7#1]
i have the same cpu thats you have but i have HP laptop but its wont work help me please , thanks 
![Screenshot 2023-10-24 091915](https://github.com/khanhmuy/hackintosh-ideapad-3-14ABA7/assets/134121009/cc45db36-e37d-479f-95b9-44e8dec4ce27)

**Comment by khanhmuy** [comment]
Please read the [OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/). You can't just expect to use an EFI config from another computer and expect it to work, it does not matter that they have the same CPU.

**Comment by AlphaNecron** [comment]
Skill issue, RTFM.
